### ISSUE TITLE
Debug warnings when creating a new post

### ISSUE THREAD

**Issue by Flerex** [Mickroz/ymwus#1]
On a completely new phpBB installation I get these warnings only when creating a new post:

> [phpBB Debug] PHP Warning: in file [ROOT]/ext/mickroz/ymwus/event/listener.php on line 118: Illegal offset type
> [phpBB Debug] PHP Warning: in file [ROOT]/ext/mickroz/ymwus/event/listener.php on line 118: Illegal offset type

Shouldn't $row be $index instead?

**Comment by Mickroz** [comment]
yes it should, but i already made a fix for it locally, i pushed them to develop branch.
